module.exports = {
  apps: [
    {
      name: "payroutine-executor",
      script: "npm",
      args: "run start:runtime",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      min_uptime: "15s",
      max_restarts: 30,
      exp_backoff_restart_delay: 200,
      restart_delay: 5000,
      kill_timeout: 15000,
      listen_timeout: 10000,
      cron_restart: "0 4 * * *",
      watch: false,
      max_memory_restart: "350M",
      env: {
        NODE_ENV: "production",
        TZ: "UTC",
      },
      out_file: "./logs/out.log",
      error_file: "./logs/error.log",
      merge_logs: true,
      time: true,
    },
  ],
};
